### ISSUE TITLE
Observe

### ISSUE THREAD

**Issue by marco-tiloca-sics** [EricssonResearch/oscore-edhoc#2]
In Section 3 "EDHOC in OSCORE", suppose that the client wants to start an observation of the requested resource, hence it includes an inner Observe 0 option.

What should the client store as request for that observation, to possibly resend in the future for re-registration/refresh?

I guess it's the same thing that the server uses as input to its step 4 later on.

**Comment by rikard-sics** [comment]
It may be sufficient to store the original CoAP request (before OSCORE protection) for re-registration purposes.

**Comment by marco-tiloca-sics** [comment]
Right, it is. Then it's just as per 7641 and 8613, and no particular text should be needed.
