### ISSUE TITLE
Double-check and fix the encoding examples

### ISSUE THREAD

**Issue by marco-tiloca-sics** [EricssonResearch/oscore-edhoc#7]
1. The OSCORE option is 0x62 09 14, i.e. 0x62 as header (following a Uri-Host option) and 0x09 14 as value). So, for readability, s/7462 0914/74 620914 --> (FP: maybe 74 64 0914)

2. In the example in Section 3.1, the following byte 0x04 should be fixed. That would mean that the EDHOC option has number 9 like the OSCORE option (i.e., delta 0) and has length 4 bytes, while what follows right after is in fact the payload marker FF (consistently with the EDHOC option always empty). Instead:

   * Double-check that the encoded EDHOC Message 3 is consistent with EDHOC.

   * Assuming the option number to be 13 or 21 (consistent with the intended properties), the byte following the OSCORE option would be 0x40 or 0xC0. (FP I assumed the option number to be 13)

3. Reflect that a Partial IV equal to 0 is used, as first outgoing request protected with the new Security Context. This means that the Partial IV is actually not even included in the OSCORE option.

4. Double check and update the byte counting.

**Comment by rikard-sics** [comment]
I believe the Partial IV is included even if it is 0x00, see for instance point 2 here: https://tools.ietf.org/html/rfc8613#page-34

**Comment by marco-tiloca-sics** [comment]
Thanks, that's correct. The presence plays a role, the value does not.
